# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'uicollectionView_lesson' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'AppCenter'
pod 'AppCenter/Analytics'
pod 'AppCenter/Crashes'
pod 'AppCenter/Distribute'

  # Pods for uicollectionView_lesson

end
